language: csharp
sudo: required
dist: trusty

mono: 3.8.0
dotnet: 1.0.0

branches:  
  only:
    - master

# solution: Andlogger.sln

script:
  # Build the source
  - cd src/Andlogger
  - dotnet restore
  - dotnet build -c Release
  
  # Back to main
  #- cd ../../
  
  # Run tests
  # - cd test/Andlogger.Tests
  # - dotnet restore
  # - dotnet test

deploy:
  provider: script
  skip_cleanup: true
  script:
    - dotnet pack -c release && dotnet nuget push *.nupkg -k $NUGET_API_KEY
  on:
    branch: master
