language: csharp
sudo: required
dotnet: 1.0.1
env: DOTNETCORE=1

solution: Andlogger.sln

script:
  # Build the source
  - cd src/Andlogger
  - dotnet restore
  - dotnet build
  
  # Back to main
  #- cd ../../
  
  # Run tests
  # - cd test/Andlogger.Tests
  # - dotnet restore
  # - dotnet test

deploy:
  provider: script
  skip_cleanup: true
  script:
    - dotnet pack -c release && dotnet nuget push *.nupkg -k $NUGET_API_KEY
  on:
    branch: master
