language: csharp
solution: Andlogger.sln
install:
  - nuget restore Andlogger.sln
script:
  - msbuild /p:Configuration=Release Andlogger.sln
deploy:
  provider: script
  skip_cleanup: true
  script:
    - cd Andlogger && nuget pack Andlogger.nuspec -Version $VERSION -IncludeReferencedProjects -Prop Configuration=Release && nuget push *.nupkg $NUGET_API_KEY -verbosity detailed
  on:
    branch: master
